package klinik.main;

import klinik.mapper.PasienMapper;
import klinik.mapper.RekamMedisMapper;
import klinik.model.Dokter;
import klinik.model.Pasien;
import klinik.model.Perawat;
import klinik.model.RekamMedis;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Queue<Pasien> antreanKlinik = new LinkedList<>();
        PasienMapper pasienMapper = new PasienMapper();
        RekamMedisMapper rekamMedisMapper = new RekamMedisMapper();
        Scanner scanner = new Scanner(System.in);

        // Dummy objects for simulation (Assuming ID 1 exists in the database)
        Dokter dokterAktif = new Dokter(1, "dr. Joshua", "Umum");
        Perawat perawatAktif = new Perawat(1, "Suster Joice", "Pagi");

        boolean isRunning = true;

        while (isRunning) {
            System.out.println("\n=== CLINIC CARE HUB ===");
            System.out.println("1. Pendaftaran Pasien Baru");
            System.out.println("2. Panggil & Periksa Pasien");
            System.out.println("3. Lihat Semua Riwayat Rekam Medis");
            System.out.println("4. Keluar");
            System.out.print("Pilih menu: ");
            
            String pilihan = scanner.nextLine();

            switch (pilihan) {
                case "1":
                    System.out.print("Masukkan Nama Pasien: ");
                    String nama = scanner.nextLine();
                    System.out.print("Masukkan Umur Pasien: ");
                    int umur = 0;
                    try {
                        umur = Integer.parseInt(scanner.nextLine());
                    } catch (NumberFormatException e) {
                        System.out.println("Umur tidak valid. Menggunakan default 0.");
                    }

                    // Create object with temporary id 0, ID will be generated by database
                    Pasien pasienBaru = new Pasien(0, nama, umur);
                    
                    // Insert to database and get object with generated ID
                    Pasien pasienTerdaftar = pasienMapper.insertPasien(pasienBaru);
                    
                    if (pasienTerdaftar.getId() != 0) {
                        antreanKlinik.add(pasienTerdaftar);
                        System.out.println("Pasien " + pasienTerdaftar.getNama() + " berhasil didaftarkan ke database dan antrean.");
                    } else {
                        System.out.println("Gagal mendaftarkan pasien ke database.");
                    }
                    break;

                case "2":
                    Pasien pasienDiperiksa = antreanKlinik.poll();
                    if (pasienDiperiksa != null) {
                        System.out.println("\n--- Memeriksa Pasien: " + pasienDiperiksa.getNama() + " ---");
                        
                        // Input Vital Data by Perawat
                        System.out.print("Suhu (C)     : ");
                        double suhu = parseDouble(scanner.nextLine());
                        System.out.print("Tensi        : ");
                        String tensi = scanner.nextLine();
                        System.out.print("Berat Badan  : ");
                        double beratBadan = parseDouble(scanner.nextLine());
                        System.out.print("Tinggi Badan : ");
                        double tinggiBadan = parseDouble(scanner.nextLine());
                        System.out.print("Keluhan      : ");
                        String keluhan = scanner.nextLine();
                        
                        // Input Medical Data by Dokter
                        System.out.print("Diagnosis    : ");
                        String diagnosis = scanner.nextLine();
                        System.out.print("Resep Obat   : ");
                        String resepObat = scanner.nextLine();

                        RekamMedis rm = new RekamMedis(
                            0, // temporary ID, will be auto-increment in DB
                            pasienDiperiksa, 
                            dokterAktif, 
                            perawatAktif, 
                            suhu, 
                            tensi, 
                            beratBadan, 
                            tinggiBadan, 
                            keluhan, 
                            diagnosis, 
                            resepObat
                        );

                        rekamMedisMapper.insertRekamMedis(rm);
                    } else {
                        System.out.println("Antrean kosong. Tidak ada pasien yang dipanggil.");
                    }
                    break;

                case "3":
                    rekamMedisMapper.tampilkanSemuaRekamMedis();
                    break;

                case "4":
                    System.out.println("Keluar dari sistem...");
                    isRunning = false;
                    break;

                default:
                    System.out.println("Menu tidak tersedia. Silakan pilih 1-4.");
                    break;
            }
        }
        scanner.close();
    }
    
    private static double parseDouble(String input) {
        try {
            return Double.parseDouble(input);
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }
}
